### ISSUE TITLE
[UWP] Crash when navigating too fast

### ISSUE THREAD

**Issue by roelvdwater** [Redth/ZXing.Net.Mobile#393]
In my UWP app, I have the following code:

```
scanner = new MobileBarcodeScanner(Dispatcher);
scanner.Dispatcher = Dispatcher;
```

Then to start scanning, I use the following code:

```
await scanner.Scan().ContinueWith(t =>
{
    HandleScanResult(t.Result);
});
```

This shows the scanning control which I can use to scan a QR code.
The problem is that when the scanning control is initializing (at this moment the scanner default has a white placeholder) and navigating back, it sometimes goes to the UnhandledException in App.g.i.cs, which contains the following message:

```
The stream number provided was invalid.
PreviewState
```

The exception contains the following message:
`The stream number provided was invalid. (Exception from HRESULT: 0xC00D36B3)
`

Is there a workaround for this problem?

**Comment by Redth** [comment]
Can you try the latest stable version 2.1.47 on NuGet?  The UWP engine had a bunch of core refactoring that should resolve these types of issues.

**Comment by Hoithebest** [comment]
Clearly something changed, but I still get the following exception:
```
This object needs to be initialized before the requested operation can be carried out.
This object needs to be initialized before the requested operation can be carried out.
```
You can reproduce this on a mobile device by repeatedly quickly opening the scanner and pressing the back button.

**Comment by Redth** [comment]
Thanks for reporting this issue!  Unforunately it took me way too long to respond 😭.  Sorry, I apologize!  Recently the source code for this project was completely refactored to modernize it.  Many PR's were included in this effort, and many bugs were hopefully fixed.  Please try out the latest 3.x series of NuGet packages (currently in prerelease).  To try and make the project more maintainable in my spare time going forward, I've decided to close all existing issues to start with a clean slate.  If you're still experiencing this issue on the newest version, please open a new issue with as much detail as possible.  Thank you for your patience and understanding!  Happy scanning!
